language: node_js
node_js:
- lts/*
notifications:
  email: false
  slack:
    secure: "$SLACK_API_TOKEN"
deploy:
  provider: npm
  email: jason@centralping.com
  skip_cleanup: true
  on:
    repo: CentralPing/sugar-cookie
    branch: master
    tags: true
  api_key:
    secure: "$NPM_API_TOKEN"
